### PR TITLE
Update build.gradle to support Gradle 7+

### PR DESCRIPTION
**Pull request by samermurad**
Except the `installArchives` task, which I really don't know how to handle, these values work; the plugin part is a pretty simple change.
I don't know how to fix the publication part though, I could try to fix it if you give me a general direction on where to look..

### CODE REVIEW

**Comment by tehong** [comment]
@maxkomarychev Is it possible for you to take a look at this PR and the question posted?  It seems that this repo needs this fix for the Gradle 7+.

**Comment by ThomasGoatITMedia** [comment]
Any idea when this will be merged in/released? I've tested this update and all seems to work fine.

**Comment by AndrewShapovalov** [comment]
@maxkomarychev could you review and merge it please?

**Comment by tr3v3r** [comment]
@maxkomarychev  same here! Could please review and merge?)

**Comment by ThomasGoatITMedia** [comment]
I've improved on this PR in a patch with patch-package
```
diff --git a/node_modules/react-native-ultimate-config/android/build.gradle b/node_modules/react-native-ultimate-config/android/build.gradle
index dcccb07..4d9fa6e 100644
--- a/node_modules/react-native-ultimate-config/android/build.gradle
+++ b/node_modules/react-native-ultimate-config/android/build.gradle
@@ -10,17 +10,17 @@
 //   original location:
 //   - https://github.com/facebook/react-native/blob/0.58-stable/local-cli/templates/HelloWorld/android/app/build.gradle
 
-def DEFAULT_COMPILE_SDK_VERSION = 28
-def DEFAULT_BUILD_TOOLS_VERSION = '28.0.3'
-def DEFAULT_MIN_SDK_VERSION = 16
-def DEFAULT_TARGET_SDK_VERSION = 28
+def DEFAULT_COMPILE_SDK_VERSION = 30
+def DEFAULT_BUILD_TOOLS_VERSION = '30.0.2'
+def DEFAULT_MIN_SDK_VERSION = 21
+def DEFAULT_TARGET_SDK_VERSION = 30
 
 def safeExtGet(prop, fallback) {
     rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
 }
 
 apply plugin: 'com.android.library'
-apply plugin: 'maven'
+apply plugin: 'maven-publish'
 
 buildscript {
     // The Android Gradle plugin is only required when opening the android folder stand-alone.
@@ -33,13 +33,13 @@ buildscript {
             jcenter()
         }
         dependencies {
-            classpath 'com.android.tools.build:gradle:3.4.1'
+            classpath 'com.android.tools.build:gradle:4.2.2'
         }
     }
 }
 
 apply plugin: 'com.android.library'
-apply plugin: 'maven'
+apply plugin: 'maven-publish'
 
 android {
     compileSdkVersion safeExtGet('compileSdkVersion', DEFAULT_COMPILE_SDK_VERSION)
@@ -75,41 +75,14 @@ dependencies {
     implementation 'com.facebook.react:react-native:+'  // From node_modules
 }
 
-def configureReactNativePom(def pom) {
-    def packageJson = new groovy.json.JsonSlurper().parseText(file('../package.json').text)
-
-    pom.project {
-        name packageJson.title
-        artifactId packageJson.name
-        version = packageJson.version
-        group = "com.reactnativeultimateconfig"
-        description packageJson.description
-        url packageJson.repository.baseUrl
-
-        licenses {
-            license {
-                name packageJson.license
-                url packageJson.repository.baseUrl + '/blob/master/' + packageJson.licenseFilename
-                distribution 'repo'
-            }
-        }
-
-        developers {
-            developer {
-                id packageJson.author.username
-                name packageJson.author.name
-            }
-        }
-    }
-}
-
 afterEvaluate { project ->
     // some Gradle build hooks ref:
     // https://www.oreilly.com/library/view/gradle-beyond-the/9781449373801/ch03.html
     task androidJavadoc(type: Javadoc) {
         source = android.sourceSets.main.java.srcDirs
         classpath += files(android.bootClasspath)
-        classpath += files(project.getConfigurations().getByName('compile').asList())
+        project.getConfigurations().implementation.setCanBeResolved(true)
+        classpath += files(project.getConfigurations().getByName('implementation').asList())
         include '**/*.java'
     }
 
@@ -140,10 +113,43 @@ afterEvaluate { project ->
 
     task installArchives(type: Upload) {
         configuration = configurations.archives
-        repositories.mavenDeployer {
-            // Deploy to react-native-event-bridge/maven, ready to publish to npm
-            repository url: "file://${projectDir}/../android/maven"
-            configureReactNativePom pom
+        def packageJson = new groovy.json.JsonSlurper().parseText(file('../package.json').text)
+
+        publishing {
+            publications {
+                mavenJava(MavenPublication) {
+                    artifactId = packageJson.name
+                    groupId = "com.reactnativeultimateconfig"
+                    version = packageJson.version
+
+                    pom {
+                        name = packageJson.title
+                        description = packageJson.description
+                        url = packageJson.repository.baseUrl
+
+                        licenses {
+                            license {
+                                name = packageJson.license
+                                url = packageJson.repository.baseUrl + '/blob/master/' + packageJson.licenseFilename
+                                distribution = 'repo'
+                            }
+                        }
+
+                        developers {
+                            developer {
+                                id = packageJson.author.username
+                                name = packageJson.author.name
+                            }
+                        }
+                    }
+                    
+                }
+            }
+            repositories {
+                maven {
+                    url = "file://${projectDir}/../android/maven"
+                }
+            }
         }
     }
 }
```

**Comment by tr3v3r** [comment]
@ThomasGoatITMedia  could you please send the norma file you've updated without DIFF markers, please?

**Review by maxkomarychev — APPROVED** [review]

**Comment by maxkomarychev** [comment]
folks I still have no capacity to test or work on this. I am assuming this has been tested by a community. I will issue version 4 shortly. thank you for contribution!

**Pull request merged**
