### PR TITLE
Web support

### LINKED ISSUE #61: Web support
It would be a killer feature if this package worked on the web as well (for universal react-native/react-native-web projects). It can *almost* be used as is with the `js_override` flag set to true, except that the getter functions in the resulting `override.js` file don't have branches for the web platform.

The bare minimum that would be needed to support this:
* Add `web` branches to the auto-generated `RN.Platform.select` calls in `override.js`.
* Add a `web` key along side the `ios` and `android` keys in platform-specific yaml config.
* Add typescript definitions for `override.js`.
* Document that `js_override` must be turned on and "react-native-ultimate-config/override" imported directly to work on the web (to avoid importing the native module).

A semi-related suggestion: why not drop the `js_override` flag and the `UltimateConfig` module reference from JavaScript entirely and just generate a pure JavaScript module containing the needed variables. This would simplify usage (zero config!) and make things work on the web and on native with the same import path. Or am I missing some benefit to pulling the JS config values from native?

If you're open to one or more of these ideas I'm happy to create a pull request.

### PR DESCRIPTION
**Pull request by elliotdickison**
It was surprisingly easy to get this working. I ended up generating a separate `index.web.js` file for the web and then using the `browser` field in package.json to tell web bundlers to use this instead of the default `index.js` file. The `browser` field is [official](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#browser) and supported by all popular bundlers. This is just a slight variation on what we discussed in #61, with the benefit that I didn't have to touch (and risk breaking) the existing native files. I also think it makes sense to keep the core react-native code in the main index.js entrypoint as this package is called **react-native**-ultimate-config after all.

A lot of the code in this PR is just a default web react app generated with create-react-app to demonstrate the new web-compatible behavior (in a separate `example-web` lerna package). I split the addition of that example web app into a separate commit to make reviewing a little easier. I can drop a lot of the create-react-app boilerplate if you'd like. The only changes I made to the example-web package were: add react-native-ultimate-config as a dependency, add the rnuc npm script, and import/render a config value in App.tsx.

I updated the spec tests to test the new index.web.js file output and then manually tested that types and config values work correctly when importing "react-native-web-config" into a web app (see `packages/example-web`).

Fixes #61

### CODE REVIEW

**Comment by maxkomarychev** [comment]
hey @elliotdickison

this is just to let you know I see your PR, but I'd need few more days to go over it.

thank you!

**Comment by elliotdickison** [comment]
Thanks! Also just to reiterate, while the PR says +49,497 😱   my changes are actually fairly minimal (see the [first commit](https://github.com/maxkomarychev/react-native-ultimate-config/pull/64/commits/f7dfc08ac5c9e5b2b2f2f71afb244179c05858f5) - roughly +30 😅). The 10 billion lines of new code are all from the example test app bootstrapped with create-react-app.

**Comment by elliotdickison** [comment]
@maxkomarychev I need to implement config in my project in a couple weeks, do you think that timeframe is realistic for getting this PR merged/published? Just trying to plan in case I’ll need to come up with a different solution. Thanks!

**Comment by maxkomarychev** [comment]
I will review it by end of the week. Sorry for the delay.

**Comment by elliotdickison** [comment]
Hey no worries - thanks for your work on this!

**Review by maxkomarychev — COMMENTED** [review]
@elliotdickison this looks great! thanks!

could you please add a little bit more documentation on this functionality into "Features" section https://github.com/maxkomarychev/react-native-ultimate-config#features (maybe even create dedicated page?).

It's currently not quite clear from homepage that this project supports web and how to use it.

Thanks!

Btw, I assume it works with `yaml` configs too, isn't it?

**Comment by elliotdickison** [comment]
Will do! Yep, yaml will take web keys I’ll document that as well.

On August 18, 2021, David Daniel ***@***.***> wrote:
> @maxkomarychev commented on this pull request.
>
> @elliotdickison <https://github.com/elliotdickison> this looks great!
> thanks!
>
> could you please add a little bit more documentation on this
> functionality into "Features" section
> <https://github.com/maxkomarychev/react-native-ultimate-
> config#features> (maybe even create dedicated page?).
>
> It's currently not quite clear from homepage that this project
> supports web and how to use it.
>
> Thanks!
>
> Btw, I assume it works with yaml configs too, isn't it?
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/maxkomarychev/react-native-ultimate-
config/pull/64#pullrequestreview-733673323>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AATIEHV62ZFPZ4QPL6LVPDDT5SZ5RANCNFSM5BN7SUDQ>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-
email>.

**Comment by elliotdickison** [comment]
Updated the docs including
- An item in the features list
- An item in the quickstart checklist
- A section in the API reference

**Comment by elliotdickison** [comment]
@maxkomarychev Just FYI looks like the Githbub action wonn't run tests until after you approve - I ran them locally though and they are passing

**Comment by maxkomarychev** [comment]
@elliotdickison approved, let's see :)

thanks!

**Comment by elliotdickison** [comment]
gitignore caught my test output file - updated the ignore rules should be good to go now

**Review by maxkomarychev — APPROVED** [review]

**Comment by maxkomarychev** [comment]
thanks @elliotdickison !!

**Pull request merged**
